<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141006213639 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE mw_t3compat_domain_model_frontendusergroup (persistence_object_identifier VARCHAR(40) NOT NULL, parent VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_B5C003B73D8E604F (parent), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mw_t3compat_domain_model_frontenduser (persistence_object_identifier VARCHAR(40) NOT NULL, account VARCHAR(40) DEFAULT NULL, address VARCHAR(255) NOT NULL, zip VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, www VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, fax VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4887C5A7D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE mw_t3compat_domain_model_frontenduser_usergroups_join (t3compat_frontenduser VARCHAR(40) NOT NULL, t3compat_frontendusergroup VARCHAR(40) NOT NULL, INDEX IDX_E3210DDCB96F1763 (t3compat_frontenduser), INDEX IDX_E3210DDC810BF92 (t3compat_frontendusergroup), PRIMARY KEY(t3compat_frontenduser, t3compat_frontendusergroup)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontendusergroup ADD CONSTRAINT FK_B5C003B73D8E604F FOREIGN KEY (parent) REFERENCES mw_t3compat_domain_model_frontendusergroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontenduser ADD CONSTRAINT FK_4887C5A7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontenduser_usergroups_join ADD CONSTRAINT FK_E3210DDCB96F1763 FOREIGN KEY (t3compat_frontenduser) REFERENCES mw_t3compat_domain_model_frontenduser (persistence_object_identifier)");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontenduser_usergroups_join ADD CONSTRAINT FK_E3210DDC810BF92 FOREIGN KEY (t3compat_frontendusergroup) REFERENCES mw_t3compat_domain_model_frontendusergroup (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontendusergroup DROP FOREIGN KEY FK_B5C003B73D8E604F");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontenduser_usergroups_join DROP FOREIGN KEY FK_E3210DDC810BF92");
		$this->addSql("ALTER TABLE mw_t3compat_domain_model_frontenduser_usergroups_join DROP FOREIGN KEY FK_E3210DDCB96F1763");
		$this->addSql("DROP TABLE mw_t3compat_domain_model_frontendusergroup");
		$this->addSql("DROP TABLE mw_t3compat_domain_model_frontenduser");
		$this->addSql("DROP TABLE mw_t3compat_domain_model_frontenduser_usergroups_join");
	}
}